[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: быстрые smoke тесты
    regression: регрессионные тесты

addopts =
    -v
    --strict-markers
    --tb=short
    --disable-warnings

allure_title = Stellar Burgers Autotests
allure_description = Автоматизированные тесты для веб-приложения Stellar Burgers